### ISSUE TITLE
Include More AWS Legos

### ISSUE THREAD

**Issue by jayasimha-raghavan-unskript** [unskript/Awesome-CloudOps-Automation#18]
**Is your feature request related to a problem? Please describe.**
Include More AWS Legos to cover EC2, S3, ECR and EKS services.

**Describe the solution you'd like**
More Legos for AWS Services would definitely be useful for future
Runbooks. It is good to have such Legos.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dougsillars** [comment]
closing WE have added dozens. Im sure there are more, but this Issue is not directly actionable
