### ISSUE TITLE
[Action]: AWS EBS Volumes Larger Than Threshold 

### ISSUE THREAD

**Issue by dougsillars** [unskript/Awesome-CloudOps-Automation#282]
### Action Name

AWS EBS Volumes Larger Than Threshold 

### Action Inputs

volume ID

### Action Outputs

% IOPS 
% volume utilized

(see comment for ChatGPTs ideas.

### Comments

Output 
% GB used
iops 

ChatGPT says: 

```
volume = ec2.Volume(volume_id)

#print the current IOPS rate for the volume
print(f"Current IOPS: {volume.iops}")

#print the maximum IOPS rate for the volume
print(f"Maximum IOPS: {volume.max_iops}")

#print the size of the volume in GB
size_gb = volume.size / 1024**3
print(f"Size: {size_gb:.2f} GB")

#print the utilization of the volume in GB
utilization_gb = volume.size * volume.volume_used_in_bytes / volume.volume_size_in_bytes / 1024**3
print(f"Utilization: {utilization_gb:.2f} GB")
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shloka-bhalgat-unskript** [comment]
There is no way to find the volume usage for an EBS. 

As @dougsillars suggested we can use the Systems Manager service as a workaround, but SSM is not set up and it requires access to SCP which needs organizational level access.

@amit-chandak-unskript please suggest what can be done here

**Comment by amit-chandak-unskript** [comment]
Yes ebs volume usage requires ssh or Ssm access to the instance. Can we use ssh for now?

**Comment by amit-chandak-unskript** [comment]
@amit-chandak-unskript needs to add some more description here

**Comment by amit-chandak-unskript** [comment]
@shloka-bhalgat-unskript we can get the usage from cloudwatch disk usage metrics https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-describing-volumes.html

I wrote a confluence page for me to test out EBS volume filling up trigger, that would help you to test this out https://unskript.atlassian.net/wiki/spaces/ENGINEERIN/pages/538214401/Enable+cloudwatch+metrics+from+EC2+instance

**Comment by shloka-bhalgat-unskript** [comment]
@amit-chandak-unskript we already have a lego to get EBS volumes with low usage from cloudwatch metrics. Here is the PR- https://github.com/unskript/Awesome-CloudOps-Automation/pull/601. 

Should I close this issue?
