### ISSUE TITLE
[Action]: Github invite user to org

### ISSUE THREAD

**Issue by dougsillars** [unskript/Awesome-CloudOps-Automation#288]
### Action Name

Github invite user to org

### Action Inputs

org
email (of new user)
role (admin, direct_manager, billing_manager)
team ids (list of teams toadd them to as well

### Action Outputs

response

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shloka-bhalgat-unskript** [comment]
Getting role as an enum instead of string.
