### ISSUE TITLE
[Action]: GitHub List organization members

### ISSUE THREAD

**Issue by dougsillars** [unskript/Awesome-CloudOps-Automation#289]
### Action Name

GitHub List organization members

### Action Inputs

org

### Action Outputs

list of members (member name, ID, type, site_admin)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shloka-bhalgat-unskript** [comment]
Same as [Issue-287](https://github.com/unskript/Awesome-CloudOps-Automation/issues/287)
