### ISSUE TITLE
[RunBook]: Ensure Classic Load Balancers Having No Instances Attached are Deleted in AWS

### ISSUE THREAD

**Issue by dougsillars** [unskript/Awesome-CloudOps-Automation#421]
### RunBook Name

AWS Delete ELB with no instances

### runbook Inputs

na

### runBook Actions

1. List all load balancers  See issue #419 
2. format list
3. Get instances for each LB: Existing Lego	
4. format output
5. Delete Load balancer see issue #417 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shloka-bhalgat-unskript** [comment]
Duplicate for #422
