### ISSUE TITLE
[RunBook]: Ensure Network Load Balancers Having No Targets Attached are Deleted in AWS

### ISSUE THREAD

**Issue by dougsillars** [unskript/Awesome-CloudOps-Automation#422]
### RunBook Name

AWS Delete NLB with no Targets

### runbook Inputs

none

### runBook Actions

List all load balancers #419 419
Get all Targets for Network Load Balancer NLB #418 418
Delete Load balancer #417

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shloka-bhalgat-unskript** [comment]
Duplicate #423
