### ISSUE TITLE
[RunBook]: AWS Set Route 53 TTL to 1 hour

### ISSUE THREAD

**Issue by dougsillars** [unskript/Awesome-CloudOps-Automation#467]
### RunBook Name

AWS Set Route 53 TTL to 1 hour

### runbook Inputs

newTTL (in seconds)
hosted zone
record name
record type

### runBook Actions

take list of inputs, and parse to run this action:
Set ttl to 3600

AWS change TTL for Route 53 Record #416 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shloka-bhalgat-unskript** [comment]
Same as 468
