### ISSUE TITLE
[RunBook]: AWS Delete Load Balancer

### ISSUE THREAD

**Issue by dougsillars** [unskript/Awesome-CloudOps-Automation#469]
### RunBook Name

AWS Delete Load Balancer

### runbook Inputs

Load balancer ID

### runBook Actions

#466 delete load balancer

### Comments

This is a healthcheck fix runbook.. it'll take the list of LB to be deleted and delete them

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shloka-bhalgat-unskript** [comment]
Duplicate for #421 #422  #423
