### ISSUE TITLE
[Action]: Check if Long Running ElastiCache Clusters Have Reserved Nodes Purchased for Them in AWS

### ISSUE THREAD

**Issue by shloka-bhalgat-unskript** [unskript/Awesome-CloudOps-Automation#574]
### HealthCheck

- [X] Is this Action a Check Action?

### Action Name

Ensure Long Running ElastiCache Clusters Have Reserved Nodes Purchased for Them in AWS

### Action Inputs

region

### Action Outputs

list of ElastiCache Clusters, region

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amit-chandak-unskript** [comment]
Same logic as redshift one i guess?
