### ISSUE TITLE
[Action]: Check if Long Running Redshift Clusters Have Reserved Nodes Purchased for Them in AWS

### ISSUE THREAD

**Issue by shloka-bhalgat-unskript** [unskript/Awesome-CloudOps-Automation#575]
### HealthCheck

- [X] Is this Action a Check Action?

### Action Name

Check if Long Running Redshift Clusters Have Reserved Nodes Purchased for Them in AWS

### Action Inputs

region

### Action Outputs

list of Redshift Clusters, region

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amit-chandak-unskript** [comment]
The way to figure this out is by 

- looking at the node type for the redshift clusters

```
amit @ ~/workspace/src/github.com/unskript/api - [EN-4476-duplicate-of-workflow-with-environment-enabled-doe] $ aws redshift describe-clusters
{
    "Clusters": [
        {
            "ClusterIdentifier": "doug-billing-3",
            "NodeType": "dc2.large",
```
- Get the type of the reserved nodes using the instructions [here](https://docs.aws.amazon.com/cli/latest/reference/redshift/describe-reserved-nodes.html)
- Now, if you have a node type for which you dont have reserved node type, then you found a cluster
- Also, we need to add logic to figure out long running redshift cluster
To figure out long running Redshift clusters, you can use the AWS Management Console or the AWS Command Line Interface (CLI) to check the cluster's uptime and usage statistics. Here are the steps:

Open the AWS Management Console and go to the Redshift dashboard.
Select the cluster you want to check.
Click on the "Cluster Performance" tab.
Check the "Uptime" metric, which shows the total duration the cluster has been running.
Review the "CPU Utilization" and "Query Throughput" charts to see how the cluster is being utilized over time. If the cluster is experiencing high utilization consistently, it may be an indication that it has been running for a long time.
You can also check the "Maintenance and Backups" tab to see the frequency and duration of backups, as well as any maintenance activities that have been performed on the cluster.
Alternatively, you can use the AWS CLI to obtain the same information by running the following command:

css
Copy code
aws redshift describe-clusters --cluster-identifier <cluster-identifier> --query 'Clusters[*].{Uptime:ElapsedTime}'
This command will return the uptime of the specified cluster. You can also use the CLI to retrieve other performance metrics for the cluster, such as CPU utilization and query throughput, by using the describe-cluster-performance command.
