### ISSUE TITLE
[Action]: Check if Long Running RDS DBs Have Reserved Instances Purchased for Them in AWS

### ISSUE THREAD

**Issue by shloka-bhalgat-unskript** [unskript/Awesome-CloudOps-Automation#579]
### HealthCheck

- [X] Is this Action a Check Action?

### Action Name

region

### Action Inputs

region

### Action Outputs

RDS DB identifiers, region

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amit-chandak-unskript** [comment]
Same logic as redshift i guess
