### ISSUE TITLE
[RunBook]:  Ensure if Buckets Have Lifecycle Policies in AWS

### ISSUE THREAD

**Issue by shloka-bhalgat-unskript** [unskript/Awesome-CloudOps-Automation#591]
### RunBook Name

Ensure if Buckets Have Lifecycle Policies in AWS

### runbook Inputs

region, bucket_names

### runBook Actions

Check if Buckets Have Lifecycle Policies in AWS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amit-chandak-unskript** [comment]
Add lifecycle policies
