### ISSUE TITLE
[RunBook]: Ensure Long Running ElastiCache Clusters Have Reserved Nodes Purchased for Them in AWS

### ISSUE THREAD

**Issue by shloka-bhalgat-unskript** [unskript/Awesome-CloudOps-Automation#593]
### RunBook Name

Ensure Long Running ElastiCache Clusters Have Reserved Nodes Purchased for Them in AWS

### runbook Inputs

region

### runBook Actions

[Check if Long Running ElastiCache Clusters Have Reserved Nodes Purchased for Them in AWS](https://github.com/unskript/Awesome-CloudOps-Automation/issues/574)

### Comments

[Check if Long Running ElastiCache Clusters Have Reserved Nodes Purchased for Them in AWS](https://github.com/unskript/Awesome-CloudOps-Automation/issues/574)

Blocked on check lego creation #574

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shloka-bhalgat-unskript** [comment]
https://github.com/unskript/Awesome-CloudOps-Automation/issues/574

@amit-chandak-unskript  Blocked on check lego creation https://github.com/unskript/Awesome-CloudOps-Automation/issues/574

**Comment by amit-chandak-unskript** [comment]
Remediation for these would be to buy reserved nodes for the node types which dont have reserved node. Now, testing this would cost us money i think:), so just code it up
