### ISSUE TITLE
[RunBook]: Check if There are RDS Instances Using Previous Gen Instance Types in AWS

### ISSUE THREAD

**Issue by shloka-bhalgat-unskript** [unskript/Awesome-CloudOps-Automation#596]
### RunBook Name

Check if There are RDS Instances Using Previous Gen Instance Types in AWS

### runbook Inputs

region

### runBook Actions

[Get Older Generation AWS RDS instances](https://github.com/unskript/Awesome-CloudOps-Automation/issues/558)

### Comments

[Get Older Generation AWS RDS instances](https://github.com/unskript/Awesome-CloudOps-Automation/issues/558)

@amit-chandak-unskript what should the remediation be here?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amit-chandak-unskript** [comment]
Can we upgrade them to newer generation type?
