### ISSUE TITLE
[RunBook]: Pods stuck in terminating state

### ISSUE THREAD

**Issue by amit-chandak-unskript** [unskript/Awesome-CloudOps-Automation#701]
### RunBook Name

Find pods stuck in terminating state 
Remediate the issue by fixing the node
Details [here](https://classic.shoreline.io/solutions/pods-stuck-in-terminating)

### runbook Inputs

namespace

### runBook Actions

Make actions based on the details https://classic.shoreline.io/solutions/pods-stuck-in-terminating

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shloka-bhalgat-unskript** [comment]
We already have a check lego and runbook for this one @amit-chandak-unskript
