### ISSUE TITLE
GCP Actions give unhelpful error when permissions are missing

### ISSUE THREAD

**Issue by abhishek-unskript** [unskript/Awesome-CloudOps-Automation#803]
**Describe the bug**
Created a new GCP credential (turned out it did not have enough access)
Tried to execute List GCP Buckets action. Got the following error

`Error: Parameter type validation failed: list indices must be integers or slices, not str`

which is not really helpful. The problem was that the service account did not have enough privileges.

**To Reproduce**
See above

**Expected behavior**
The error should mention something like "Access Denied", or "Not enough permissions"

**Screenshots**
See attached

**Desktop (please complete the following information):**
 - OS: MacOS
 - Chrome

<img width="1076" alt="Screenshot 2023-07-23 at 11 42 44 PM" src="https://github.com/unskript/Awesome-CloudOps-Automation/assets/74047156/7d0dc69a-78ea-4e43-935d-703f941d18c6">

**Comment by shloka-bhalgat-unskript** [comment]
@abhishek-unskript please review [this](https://github.com/unskript/Awesome-CloudOps-Automation/pull/804) PR.
